___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries. For more info on why you would want to use Arrays instead of lists, check out this great [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

We will only learn the basics of NumPy, to get started we need to install it!

## Installation Instructions

**It is highly recommended you install Python using the Anaconda distribution to make sure all underlying dependencies (such as Linear Algebra libraries) all sync up with the use of a conda install. If you have Anaconda, install NumPy by going to your terminal or command prompt and typing:**
    
    conda install numpy
    
**If you do not have Anaconda and can not install it, please refer to [Numpy's official documentation on various installation instructions.](http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Using NumPy

Once you've installed NumPy you can import it as a library:

In [23]:
import numpy as np
print (np.__version__)

1.26.4


Numpy has many built-in functions and capabilities. We won't cover them all but instead we will focus on some of the most important aspects of Numpy: vectors,arrays,matrices, and number generation. Let's start by discussing arrays.

# Numpy Arrays

NumPy arrays are the main way we will use Numpy throughout the course. Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

Let's begin our introduction by exploring how to create NumPy arrays.

## Creating NumPy Arrays

### From a Python List

We can create an array by directly converting a list or list of lists:

In [26]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [31]:
arr = np.array(my_list)

In [33]:
arr

array([1, 2, 3])

In [35]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [37]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

There are lots of built-in ways to generate Arrays

### arange

Return evenly spaced values within a given interval.

In [42]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
np.arange(0,11,2) # with a step size of 2

array([ 0,  2,  4,  6,  8, 10])

### zeros and ones

Generate arrays of zeros or ones

In [49]:
np.zeros(3)

array([0., 0., 0.])

In [57]:
np.zeros((5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [80]:
np.ones(3)

array([1., 1., 1.])

In [91]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [93]:
np.ones((1,1))

array([[1.]])

### linspace
Return evenly spaced numbers over a specified interval.

In [96]:
np.linspace(0,10,3) # will return 3 evenly spaced number between 0 and 10

array([ 0.,  5., 10.])

In [98]:
np.linspace(0,10,50) # will return 50 evenly spaced number between 0 and 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye

Creates an identity matrix - a two-dimensional square matrix and a diagonal of 1s with all the rest 0s

In [104]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

Numpy also has lots of ways to create random number arrays:

### rand
Create an array of the given shape and populate it with
random samples from a uniform distribution
over ``[0, 1)``.

In [115]:
np.random.rand(2)

array([0.24974606, 0.07551603])

In [117]:
np.random.rand(5,5)

array([[0.80331207, 0.12478581, 0.64463554, 0.48715344, 0.09858043],
       [0.33451975, 0.63166204, 0.86330828, 0.60495201, 0.56114879],
       [0.05635117, 0.35179961, 0.91899986, 0.37356459, 0.40893782],
       [0.67373025, 0.35464591, 0.65778986, 0.2311624 , 0.1317087 ],
       [0.45421228, 0.81294869, 0.0155186 , 0.40562382, 0.84151812]])

### randn

Return a sample (or samples) from the "standard normal" distribution centered around 0. Unlike rand which is uniform:

In [127]:
np.random.randn(2)

array([ 0.14135988, -0.2100499 ])

In [131]:
np.random.randn(5,5)

array([[ 0.63864818,  0.39533442, -2.23196479,  1.84694997, -1.51037709],
       [-0.61537899,  0.59151115,  0.92194488, -2.44716617, -1.33772402],
       [ 0.49772662, -1.18915265, -0.26064622, -1.66367169,  1.70855769],
       [-0.54104639,  1.99233257, -0.19744009, -1.53045574,  2.08729299],
       [ 1.74487003, -0.46759574,  0.31299961,  0.85133044, -0.82987545]])

### randint
Return random integers from `low` (inclusive) to `high` (exclusive).

In [134]:
np.random.randint(1,100)

16

In [142]:
np.random.randint(1,100,10)

array([98,  7, 49, 31, 57, 52,  5, 48, 49, 67])

## Array Attributes and Methods

Let's discuss some useful attributes and methods or an array:

In [152]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [154]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [156]:
ranarr

array([ 4, 42, 49,  6, 30, 20, 34, 22, 11, 41])

## Reshape
Returns an array containing the same data with a new shape.

In [163]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [165]:
ranarr.reshape(2,5)

array([[ 4, 42, 49,  6, 30],
       [20, 34, 22, 11, 41]])

### max,min,argmax,argmin

These are useful methods for finding max or min values. Or to find their index locations using argmin or argmax

In [168]:
ranarr

array([ 4, 42, 49,  6, 30, 20, 34, 22, 11, 41])

In [170]:
ranarr.max()

49

In [174]:
ranarr.argmax() # index of max

2

In [176]:
ranarr.min()

4

In [178]:
ranarr.argmin()

0

## Shape

Shape is an attribute that arrays have (not a method):

In [183]:
# Vector
arr.shape

(25,)

In [185]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [187]:
arr.reshape(1,25).shape

(1, 25)

In [189]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [191]:
arr.reshape(25,1).shape

(25, 1)

### dtype

You can also grab the data type of the object in the array:

In [197]:
arr.dtype

dtype('int32')

# Great Job!