___

<a href='http://www.pieriandata.com'> <img src='../Pierian_Data_Logo.png' /></a>
___

# NumPy Indexing and Selection

In this lecture we will discuss how to select elements or groups of elements from an array.

In [3]:
import numpy as np

In [5]:
#Creating sample array
arr = np.arange(0,11)

In [7]:
#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket Indexing and Selection
The simplest way to pick one or some elements of an array looks very similar to python lists:

In [10]:
#Get a value at an index
arr[8]

8

In [12]:
#Get values in a range
arr[1:5]

array([1, 2, 3, 4])

In [14]:
#Get values in a range
arr[0:5]

array([0, 1, 2, 3, 4])

In [16]:
# values up until index 6
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [20]:
# values starting from index 5
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

## Broadcasting

Numpy arrays differ from a normal Python list because of their ability to broadcast:

In [25]:
#Setting a value with index range (Broadcasting) -> broadcasting value 100 to index 0 to 4
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [27]:
# Reset array, we'll see why I had to reset in  a moment
arr = np.arange(0,11)

#Show
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [31]:
#Change Slice -> broadcaset the whole slice_of_arr with 99
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

Now note the changes also occur in our original array!

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Data is not copied, it's a view of the original array! This avoids memory problems!

In [40]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [42]:
arr_copy[:] = 100

In [44]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

## Indexing a 2D array (matrices)

The general format is **arr_2d[row][col]** or **arr_2d[row,col]**. I recommend usually using the comma notation for clarity.

In [51]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [53]:
#Indexing row
arr_2d[1]


array([20, 25, 30])

In [55]:
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1][0]

20

In [57]:
# Getting individual element value
arr_2d[1,0]

20

In [67]:
# 2D array slicing

#Shape (2,2) from top right corner
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [77]:
#top two rows

arr_2d[:2,0] # or arr_2d[:2]

array([ 5, 20])

In [93]:
#Shape bottom row
arr_2d[2] #or arr_2d[2:,] or arr_2d[2:,:]

array([35, 40, 45])

In [95]:
#Shape bottom row
arr_2d[2,:]

array([35, 40, 45])

## Selection

Let's briefly go over how to use brackets for selection based off of comparison operators.

In [99]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [101]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [129]:
bool_arr = arr>4    #Boolean array

In [131]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [133]:
arr[bool_arr] #conditionally select elements tahat are True

array([ 5,  6,  7,  8,  9, 10])

In [135]:
arr[arr>2]  #in one step

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [137]:
arr 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [154]:
x = 2
arr[arr>x] # a new array is made, unlike the slicing which is just a view 

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [156]:
x = 3
arr[arr<3]

array([1, 2])

## Exercise

In [159]:
arr_2d = np.arange(50).reshape(5,10)

In [161]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [163]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

# Great Job!
